{% set name = "GeneralisedFormanRicci" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GeneralisedFormanRicci-{{ version }}.tar.gz
  sha256: 185cef1674ebfdc31ccfba96b7457d08abbeeea190ee1e1ffd99b96a5555ab1b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - scipy
    - networkx
    - gudhi
    - python >=3.6

test:
  imports:
    - GeneralisedFormanRicci
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ExpectozJJ/GeneralisedFormanRicci
  license: Apache-2.0
  license_family: APACHE
  # License file manually packaged. See https://github.com/ExpectozJJ/GeneralisedFormanRicci/pull/2
  license_file: LICENSE
  summary: A class to compute the Generalised Forman-Ricci curvature for a Simplicial Complex from a given point cloud data.
  description: |
    A class to compute the Generalised Forman-Ricci curvature for a Simplicial Complex from a given point cloud data.
  doc_url: https://github.com/ExpectozJJ/GeneralisedFormanRicci
  dev_url: https://github.com/ExpectozJJ/GeneralisedFormanRicci

extra:
  recipe-maintainers:
    - ExpectozJJ
